Repository googleapis/java-dns, pull requests merged in 2020-12, with the labels that each got.

#275 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full

#278 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dns, automerge, cla: yes

#284 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dns, automerge, cla: yes

#285 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full

#276 feat: expose DNSSEC options of ManagedZones
  src/main/java/com/google/cloud/dns/Dns.java
  src/main/java/com/google/cloud/dns/Zone.java
  src/main/java/com/google/cloud/dns/ZoneInfo.java
  src/test/java/com/google/cloud/dns/ZoneInfoTest.java
  src/test/java/com/google/cloud/dns/it/ITDnsTest.java
Labels: api: dns, cla: yes

#289 feat: add supports of labels while creating managed zone
  clirr-ignored-differences.xml
  src/main/java/com/google/cloud/dns/Dns.java
  src/main/java/com/google/cloud/dns/Zone.java
  src/main/java/com/google/cloud/dns/ZoneInfo.java
  src/test/java/com/google/cloud/dns/ZoneInfoTest.java
  src/test/java/com/google/cloud/dns/it/ITDnsTest.java
Labels: api: dns, cla: yes

#291 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full, merge
