Repository googleapis/java-dns, pull requests merged in 2021-09, with the labels that each got.

#513 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: dns, automerge, context: full

#519 chore: regenerate common templates
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, api: dns, automerge, context: full

#518 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: dns, automerge

#520 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
Labels: cla: yes, api: dns

#531 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: dns

#525 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: dns, automerge

#535 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: dns, automerge

#536 chore: change branch master to main in github configurations
  README.md
Labels: cla: yes, api: dns, automerge
