Repository googleapis/java-dns, pull requests merged in 2021-05, with the labels that each got.

#396 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: none

#397 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full

#401 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dns, automerge, cla: yes

#409 chore: ignore createZoneWithError tests
  src/test/java/com/google/cloud/dns/it/ITDnsTest.java
Labels: api: dns, automerge, cla: yes

#410 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dns, automerge, cla: yes

#411 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dns, automerge, cla: yes

#402 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full

#413 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full

#415 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: dns, automerge, cla: yes

#417 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full

#420 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full
